// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuuBQVVHFXP-pFPhe-t7j3YqDSsnD13iE',
    appId: '1:615213173972:web:9fc7e47422ea927ce2ff41',
    messagingSenderId: '615213173972',
    projectId: 'woven-rush-413614',
    authDomain: 'woven-rush-413614.firebaseapp.com',
    storageBucket: 'woven-rush-413614.appspot.com',
    measurementId: 'G-PZ9PPC601E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTc8lo-oiyAht8wRKB_DAk7Vuw2a4J80',
    appId: '1:615213173972:android:65e78a2a5f5d5857e2ff41',
    messagingSenderId: '615213173972',
    projectId: 'woven-rush-413614',
    storageBucket: 'woven-rush-413614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANnwr4sWvouVU9IxUp5IuEL_omdImdD7k',
    appId: '1:615213173972:ios:8314489e451b8c71e2ff41',
    messagingSenderId: '615213173972',
    projectId: 'woven-rush-413614',
    storageBucket: 'woven-rush-413614.appspot.com',
    iosBundleId: 'com.example.mapsTask',
  );
}
